name: Validation Build 

on:
  pull_request:
    branches:
      - staging
      - main
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v4

    - name: Check that data is OK
      run: . ./.github/scripts/check-unique-guid.sh
    

    - name: Check that data is OK
      run: . ./.github/scripts/check-unique-guid.sh
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        
    - run: npm install

    - run: gulp build

    - name: Get current time
      uses: josStorer/get-current-time@v2.1.1
      id: current-time
      with:
        format: DD-MM-YYYY

    - name: inject date
      uses: cschleiden/replace-tokens@v1.2
      with:
        files: '["**/*.html"]'
      env:
        BUILD_DATE: "${{ steps.current-time.outputs.formattedTime }}"

    - name: Run the Transformer
      run: |
        pushd ./data/scripts
        pip3 install pandas
        python ./transform_to_ft.py
        popd

    - name: Run the Transformer
      run: |
        pushd ./data/scripts
        pip3 install pandas
        python ./transform_to_ft.py
        popd

    - uses: actions/upload-artifact@v4
      with:
        name: CheckList
        path: dist
