name: Validarere tion Build 

on:
  pull_request:
    branches:
      - staging

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: Cache node modules
      uses: actions/cache@v2
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        
    - run: npm install

    - run: gulp build

    - name: Get current time
      uses: srfrnk/current-time@master
      id: current-time
      with:
        format: DD-MM-YYYY

    - uses: cschleiden/replace-tokens@v1
      name: inject date
      with:
        files: '["**/*.html"]'
      env:
        BUILD_DATE: "${{ steps.current-time.outputs.formattedTime }}"
 
    - uses: actions/upload-artifact@v1
      with:
        name: CheckList
        path: dist
